# Generated by Django 2.2.5 on 2022-02-03 21:13

import apps.home.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='nombre')),
                ('web', models.CharField(max_length=128, verbose_name='pagina web')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_subsistema', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_subsistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='nombre')),
                ('prefesional', models.BooleanField(default=False)),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_oferta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_oferta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=128)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=400, verbose_name='Descripción')),
                ('link', models.CharField(max_length=400, verbose_name='link de noticia')),
                ('imagen', models.ImageField(upload_to=apps.home.models.imagenNoticia_path, verbose_name='Imagen de noticia')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subsistema', verbose_name='Subsistema perteneciente')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_noticia', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_noticia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='nombre')),
                ('distrito', models.PositiveSmallIntegerField(blank=True, verbose_name='Distrito (Managua)')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_municipio', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_municipio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('direccion', ckeditor.fields.RichTextField(max_length=256, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('web', models.CharField(max_length=128, verbose_name='Sitio web')),
                ('latitud', models.CharField(blank=True, max_length=50, verbose_name='Latitud (Georeferencia)')),
                ('longitud', models.CharField(blank=True, max_length=50, verbose_name='Longitud (Georeferencia)')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_municipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Municipio', verbose_name='Municipio')),
                ('id_subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subsistema', verbose_name='Subsistema perteneciente')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_institucion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_institucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=128)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', ckeditor.fields.RichTextField(max_length=400, verbose_name='Descripción')),
                ('link', models.CharField(max_length=400, verbose_name='link de noticia')),
                ('imagen', models.ImageField(upload_to=apps.home.models.imagenEvento_path, verbose_name='Imagen de evento')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subsistema', verbose_name='Subsistema perteneciente')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_evento', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Detalleoferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Institucion', verbose_name='Institucion')),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Oferta', verbose_name='Carrera/Curso')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_detalleoferta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_detalleoferta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='nombre')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='orden')),
                ('portada', models.ImageField(upload_to=apps.home.models.imagenDepartamento_path, verbose_name='Imagen de portada')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_departamento', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_departamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField(default=2021, verbose_name='Año')),
                ('estudiantes_h', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de sexo Masculino')),
                ('estudiantes_m', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de sexo femenino')),
                ('edad_3a5', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de con rango de eda 3 -5 años')),
                ('edad_6a11', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de con rango de eda 6 -11 años')),
                ('edad_12a18', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de con rango de eda 12 -18 años')),
                ('edad_18', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes mayores de 18 años')),
                ('estudiante_r', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de la zona Rural')),
                ('estudiante_u', models.PositiveSmallIntegerField(verbose_name='Cantidad de estudiantes de la zona Urbana')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departamento', verbose_name='Departamento')),
                ('id_subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subsistema', verbose_name='Subsistema perteneciente')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_dashboard', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Subsistema',
                'ordering': ['id_subsistema'],
            },
        ),
    ]
