# Generated by Django 2.2.5 on 2022-02-03 22:48

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='portada',
            field=models.ImageField(blank=True, upload_to=apps.home.models.imagenDepartamento_path, verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='web',
            field=models.CharField(blank=True, max_length=128, verbose_name='Sitio web'),
        ),
    ]
