# Generated by Django 2.2.5 on 2022-02-04 13:55

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_municipio_id_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='detalleoferta',
            options={'verbose_name_plural': 'Ofertas por institucion'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='subsistema',
            options={'verbose_name_plural': 'Subsistemas'},
        ),
        migrations.AddField(
            model_name='institucion',
            name='foto',
            field=models.ImageField(blank=True, upload_to=apps.home.models.imagenInstituciones_path, verbose_name='Imagen de la Institucion o Centro'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC/CNU'), (2, 'CENTRO'), (3, 'ECUELA NORMAL')], default=1, verbose_name='Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id_subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Subsistema', verbose_name='Subsistema perteneciente'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='detalleoferta',
            name='id_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Institucion', verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='detalleoferta',
            name='id_oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Oferta', verbose_name='Carrera/Curso'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Subsistema', verbose_name='Subsistema perteneciente'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='id_municipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='id_subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Subsistema', verbose_name='Subsistema perteneciente'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id_subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Subsistema', verbose_name='Subsistema perteneciente'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subsistema',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_modalidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_modalidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.AddField(
            model_name='institucion',
            name='id_modalidad',
            field=models.ForeignKey(blank=True, default=1.0, on_delete=django.db.models.deletion.PROTECT, to='home.Modalidad', verbose_name='Modalidad'),
            preserve_default=False,
        ),
    ]
