# Generated by Django 2.2.5 on 2022-02-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220204_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='orden',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='detallemodalidad',
            name='id_modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Modalidad', verbose_name='Modalidad'),
        ),
    ]
