# Generated by Django 2.2.5 on 2022-02-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220204_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='id_departamento',
            field=models.ForeignKey(default=0.0004945598417408506, on_delete=django.db.models.deletion.PROTECT, to='home.Departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_departamento',
            field=models.ForeignKey(default=0.0004945598417408506, on_delete=django.db.models.deletion.PROTECT, to='home.Departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Evento'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Noticia'),
        ),
    ]
