# Generated by Django 2.2.5 on 2022-02-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220204_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleoferta',
            name='id_institucion',
        ),
        migrations.RemoveField(
            model_name='detalleoferta',
            name='id_oferta',
        ),
        migrations.RemoveField(
            model_name='detalleoferta',
            name='usuario_grabacion',
        ),
        migrations.RemoveField(
            model_name='detalleoferta',
            name='usuario_modificacion',
        ),
        migrations.AddField(
            model_name='institucion',
            name='id_modalidad',
            field=models.ManyToManyField(blank=True, to='home.Modalidad', verbose_name='Modalidades'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='id_oferta',
            field=models.ManyToManyField(blank=True, to='home.Oferta', verbose_name='Ofertas que posee la institucion'),
        ),
        migrations.DeleteModel(
            name='DetalleModalidad',
        ),
        migrations.DeleteModel(
            name='Detalleoferta',
        ),
    ]
