# Generated by Django 2.2.5 on 2022-02-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220204_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO ESCOLAR'), (3, 'ESCUELA NORMAL'), (4, 'UNIVERSIDAD ESTABLECIDA'), (5, 'UNIVERSIDAD MIEMBRO')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
