# Generated by Django 2.2.5 on 2022-02-07 14:41

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_subsistema_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=-2017, editable=True, populate_from='nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO ESCOLAR'), (3, 'ESCUELA NORMAL'), (4, 'UNIVERSIDAD ESTABLECIDA'), (5, 'UNIVERSIDAD MIEMBRO'), (6, 'CENTROS PRIVADOS INATEC')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
