# Generated by Django 2.2.5 on 2022-02-07 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220207_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Descripción'),
        ),
    ]
