# Generated by Django 2.2.5 on 2022-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220207_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='docente_h',
            field=models.PositiveSmallIntegerField(default=-2017, verbose_name='Cantidad de docentes de sexo Masculino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='docente_m',
            field=models.PositiveSmallIntegerField(default=-2017, verbose_name='Cantidad de docentes de sexo femenino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2022, verbose_name='Año'),
        ),
    ]
