# Generated by Django 2.2.5 on 2022-02-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220207_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(max_length=60, verbose_name='Teléfono'),
        ),
    ]
