# Generated by Django 2.2.5 on 2022-02-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220207_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='prefesional',
        ),
    ]
