# Generated by Django 2.2.5 on 2022-02-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_oferta_prefesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud (Georeferencia)'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud (Georeferencia)'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud (Georeferencia)'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud (Georeferencia)'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR'), (4, 'ESCUELA NORMAL'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO')], default=1, verbose_name='Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR'), (4, 'ESCUELA NORMAL'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
