# Generated by Django 2.2.5 on 2022-02-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220208_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='latitud_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud (Georeferencia)'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='longitud_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud (Georeferencia)'),
        ),
    ]
