# Generated by Django 2.2.5 on 2022-02-09 15:35

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220208_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Video Presentacion Nosotros',
            },
        ),
        migrations.AddField(
            model_name='subsistema',
            name='portada',
            field=models.ImageField(default=-2022, upload_to=apps.home.models.imagenSubsistema_path, verbose_name='Imagen Portada'),
            preserve_default=False,
        ),
    ]
