# Generated by Django 2.2.5 on 2022-02-09 15:54

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220209_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videohome',
            options={'verbose_name': 'Video Presentacion Inicio'},
        ),
        migrations.AlterField(
            model_name='videohome',
            name='file',
            field=models.FileField(null=True, upload_to=apps.home.models.Video_path, verbose_name='Video Presentacion Inicio'),
        ),
        migrations.AlterField(
            model_name='videonosotros',
            name='video',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Video Presentacion Nosotros'),
        ),
    ]
