# Generated by Django 2.2.5 on 2022-02-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220209_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_alf',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes Alfabetizados /Mined'),
            preserve_default=False,
        ),
    ]
