# Generated by Django 2.2.5 on 2022-02-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_dashboard_estudiantes_alf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='docente_rcp',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de docentes Reconocimiento de Competencia Profesionales /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_c',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes Capacitacion /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_cap_idioma',
            field=models.PositiveSmallIntegerField(blank=True, default=0.0004945598417408506, verbose_name='Cantidad de estudiantes Idiomas /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_fd',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes Formacion Docente /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_omo',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Cantidad de estudiantes Escuela Municipal de Oficio /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiantes_tec',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Cantidad de estudiantes Educación Tecnica en Campo /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='modalidad',
            field=models.IntegerField(choices=[(1, 'Formacion Presencial'), (5, 'Virtual')], default=1, verbose_name='Modalidad - INATEC'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sector',
            field=models.IntegerField(choices=[(2, 'Agropecuario y Forestal'), (3, 'Industria y Construccion'), (4, 'Comercio y Servicio')], default=1, verbose_name='Sector - INATEC'),
        ),
    ]
