# Generated by Django 2.2.5 on 2022-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220211_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='docente_rcp',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='sector',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_af',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes sector  Agropecuario y Forestal /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_cs',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Cantidad de estudiantes sector Comercio y Servicio /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_fp',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes sector Forma presencial /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_fv',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Cantidad de estudiantes sector Forma virtual /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_ic',
            field=models.PositiveSmallIntegerField(blank=True, default=-2022, verbose_name='Cantidad de estudiantes sector industria y Comercial /Inatec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_rcp',
            field=models.PositiveSmallIntegerField(blank=True, default=0.0004945598417408506, verbose_name='Cantidad de estudiantes Reconocimiento de Competencia Profesionales /Inatec'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO')], default=1, verbose_name='Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
