# Generated by Django 2.2.5 on 2022-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220214_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL - PUBLICA'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO'), (4, 'ESCUELA NORMAL - PRIVADA')], default=1, verbose_name='Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO PRIVADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL - PUBLICA'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO'), (4, 'ESCUELA NORMAL - PRIVADA')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
