# Generated by Django 2.2.5 on 2022-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20220214_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_af',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes sector  Agropecuario y Forestal /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_cs',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes sector Comercio y Servicio /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_fp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Forma presencial /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_fv',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Forma virtual /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_ic',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes sector industria y Comercial /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiante_rcp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Reconocimiento de Competencia Profesionales /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_alf',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Alfabetizados /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_c',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Capacitacion /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_cap_idioma',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Idiomas /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_e',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Especial /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_f',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Formacion Docente /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_fd',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Formacion Docente /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_i',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Inicial /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_omo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Escuela Municipal de Oficio /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_p',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Primaria /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_s',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Secundaria /Mined'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_t',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Bachiller Tecnico /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_te',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Tecnico Especialista /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_tec',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Educación Tecnica en Campo /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_tg',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Tecnico General /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_ts',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Tecnico Superior /Inatec'),
        ),
    ]
