# Generated by Django 2.2.5 on 2022-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20220214_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_d',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Doctor /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_em',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Especialista Medico /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_es',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Especialista /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_l',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Licenciado o Equivalente /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_m',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Master /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='estudiante_tes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes  Técnico Superios /CNU'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_t',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Bachiller Técnico /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_te',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Técnico Especialista /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_tg',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Técnico General /Inatec'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='estudiantes_ts',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Técnico Superior /Inatec'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO ACREDITADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL - PUBLICA'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO'), (8, 'ESCUELA NORMAL - PRIVADA')], default=1, verbose_name='Tipo Institucion'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'INATEC'), (2, 'CENTRO ACREDITADO - INATEC'), (3, 'CENTRO ESCOLAR - PUBLICO'), (4, 'ESCUELA NORMAL - PUBLICA'), (5, 'UNIVERSIDAD LEGALMENTE CONSTITUIDA'), (6, 'UNIVERSIDAD MIEMBRO'), (7, 'CENTRO ESCOLAR - PRIVADO'), (8, 'ESCUELA NORMAL - PRIVADA')], default=1, verbose_name='Tipo Institucion'),
        ),
    ]
