# Generated by Django 2.2.5 on 2022-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='sector',
            field=models.CharField(blank=True, choices=[(2, 'Agropecuario y Forestal'), (3, 'Industria y Construccion'), (4, 'Comercio y Servicio')], max_length=10, verbose_name='Sector - Inatec'),
        ),
    ]
