# Generated by Django 2.2.5 on 2022-02-16 16:04

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220216_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_actual',
            field=models.ImageField(blank=True, upload_to=apps.home.models.imagenLogo_path, verbose_name='Imagen Logo Actual'),
        ),
    ]
