# Generated by Django 2.2.5 on 2022-02-16 20:42

import apps.home.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0036_auto_20220216_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionUnesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_clasificacionunesco', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_clasificacionunesco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clasificación Unesco',
            },
        ),
        migrations.CreateModel(
            name='PatrimonioUnesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('url_unesco', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL Unesco')),
                ('link_2', models.URLField(blank=True, max_length=512, null=True, verbose_name='Link fuente 2')),
                ('link_3', models.URLField(blank=True, max_length=512, null=True, verbose_name='Link fuente 3')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenNoticia_path, verbose_name='Banner del Patrimonio')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.ClasificacionUnesco', verbose_name='Clasificacion')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_patrimoniounesco', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_patrimoniounesco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patrimonios Unesco',
            },
        ),
    ]
