# Generated by Django 2.2.5 on 2022-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_clasificacionunesco_patrimoniounesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniounesco',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud (Georeferencia)'),
        ),
        migrations.AddField(
            model_name='patrimoniounesco',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud (Georeferencia)'),
        ),
    ]
