# Generated by Django 2.2.5 on 2022-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220216_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniounesco',
            name='latitud_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud 2(Georeferencia)'),
        ),
        migrations.AddField(
            model_name='patrimoniounesco',
            name='longitud_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud 2(Georeferencia)'),
        ),
    ]
