# Generated by Django 2.2.5 on 2022-02-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220216_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniounesco',
            name='id_municipio',
            field=models.ManyToManyField(blank=True, to='home.Municipio', verbose_name='Municipios que l@ conforman'),
        ),
    ]
