# Generated by Django 2.2.5 on 2022-02-16 23:19

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_patrimoniounesco_id_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniounesco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenPatrimonio2_path, verbose_name='Imagen Tarjeta'),
        ),
        migrations.AlterField(
            model_name='patrimoniounesco',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenPatrimonio_path, verbose_name='Banner del Patrimonio'),
        ),
        migrations.AlterField(
            model_name='subsistema',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenSubsistema2_path, verbose_name='Imagen Default Tarjeta'),
        ),
        migrations.AlterField(
            model_name='subsistema',
            name='imagen_cp',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenSubsistema3_path, verbose_name='Imagen Default Tarjeta - Centro Pivado/INATEC'),
        ),
    ]
