# Generated by Django 2.2.5 on 2022-02-18 23:14

import apps.home.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0042_auto_20220217_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPlataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_plataforma', models.ImageField(blank=True, upload_to=apps.home.models.imagenbannerPlataforma_path, verbose_name='Banner Principal Plataformas')),
            ],
            options={
                'verbose_name': 'Banner Principal Plataforma',
            },
        ),
        migrations.AlterModelOptions(
            name='bannerpatrimonio',
            options={'verbose_name': 'Banner Principal Patrimonio'},
        ),
        migrations.CreateModel(
            name='PlataformaVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.home.models.imagenPlataforma_path, verbose_name='Imagen Tarjeta')),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=1, verbose_name='Estado')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_plataformavirtual', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_plataformavirtual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plataformas virtuales',
            },
        ),
    ]
