# Generated by Django 2.2.5 on 2022-02-19 03:15

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20220218_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsistema',
            name='pdf',
            field=models.FileField(null=True, upload_to=apps.home.models.Pdf_path, verbose_name='PDF de las ofertas'),
        ),
    ]
