# Generated by Django 2.2.5 on 2022-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_subsistema_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='egresado_h',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de estudiantes egresados de sexo Masculino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_m',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de estudiantes egresados de sexo femenino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_r',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de estudiantes egresados de la zona Rural'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_u',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de estudiantes egresados de la zona Urbana'),
            preserve_default=False,
        ),
    ]
