# Generated by Django 2.2.5 on 2022-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20220219_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformavirtual',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
