# Generated by Django 2.2.5 on 2022-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_plataformavirtual_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='egresado_c',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Capacitacion /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_cap_idioma',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Idiomas /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_fd',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Formacion Docente /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_l',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado  Licenciado o Equivalente /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_omo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Escuela Municipal de Oficio /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_p',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado  Posgrado /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_rcp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Reconocimiento de Competencia Profesionales /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_t',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Bachiller Técnico /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_te',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado  Técnico Especialista /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_tec',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Educación Tecnica en Campo /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_tes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Técnico Superios /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_tg',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Técnico General /Inatec'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='egresado_ts',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Egresado Técnico Superior /Inatec'),
        ),
    ]
