# Generated by Django 2.2.5 on 2022-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_institucion_codigoestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='becas_a',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Becas Aranceles /CNU'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='becas_e',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Cantidad de estudiantes Becas Especiales /CNU'),
        ),
    ]
