# Generated by Django 2.2.5 on 2022-02-21 17:54

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20220221_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohome',
            name='file2',
            field=models.FileField(null=True, upload_to=apps.home.models.Video2_path, verbose_name='Video Presentacion Inicio para movil'),
        ),
    ]
