# Generated by Django 2.2.5 on 2022-02-21 21:10

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_videohome_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformavirtual',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.bannerPlataforma_path, verbose_name='Banner Principal'),
        ),
    ]
